In [1]:
%load_ext autoreload
%autoreload 2
import torch
import main

In [2]:
main.determinant_2x2(torch.Tensor([[1, 0], [0, 1]]))

tensor(1.)

In [3]:
main.matrix_multiply(torch.zeros(3, 4), torch.zeros(4, 2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
main.tensor_multiply(torch.zeros(4), torch.zeros(4, 2))

tensor([0., 0.])

In [5]:
main.tensor_multiply(torch.zeros(2, 3, 4), torch.zeros(4, 2))

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [6]:
main.pointwise_multiply(torch.ones(2, 3, 4), torch.ones(1, 1, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [7]:
main.random_chisq(5)

tensor([0.0206, 1.2450, 0.5967, 0.8929, 0.8557])

In [8]:
main.tail(torch.arange(7, dtype=float))

tensor([1., 2., 3., 4., 5., 6.], dtype=torch.float64)

In [27]:
synthetic = main.generate(
    p=5,
    k=3,
    n=150,
    sigma=0.1
)

In [28]:
x = synthetic.x
y = synthetic.y
beta_hat = main.multiple_linear_regression(x, y)

In [29]:
synthetic.beta

tensor([[0.1321, 0.1523, 0.6559],
        [0.0217, 0.3609, 0.7609],
        [0.6095, 0.9824, 0.0342],
        [0.1445, 0.4515, 0.1965],
        [0.5076, 0.5499, 0.1848]])

In [30]:
beta_hat

tensor([[0.1469, 0.1812, 0.6790],
        [0.0529, 0.3623, 0.7834],
        [0.6396, 1.0071, 0.0484],
        [0.1563, 0.4698, 0.2198],
        [0.5133, 0.5760, 0.1992]])

In [31]:
yhat = main.predict(beta_hat, x)
err = y - yhat
r2 = 1 - (err ** 2).sum() / (y ** 2).sum()
print(f"R2 is {r2}, R is {r2 ** 0.5}")

R2 is 0.9991446137428284, R is 0.999572217464447
